; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif8266@4.2.1
framework = arduino
monitor_speed = 115200
monitor_filters =esp8266_exception_decoder
custom_prog_version = 1.2.0-dev-0.2
build_flags = 
	-DVERSION=${this.custom_prog_version}
	-DPIO_SRC_NAM="Solar2MQTT-ESP8266"
	-DESP8266 -DATOMIC_FS_UPDATE
	-DWS_MAX_QUEUED_MESSAGES=2
	-DWSL_MAX_WS_CLIENTS=1
	-DCONFIG_ASYNC_TCP_QUEUE_SIZE=4
	-DCONFIG_ASYNC_TCP_STACK_SIZE=2048
board_build.lwip_variant = low_memory

extra_scripts = pre:tools/mini_html.py
	pre:tools/pre_compile.py
	post:tools/post_compile.py
lib_deps = 
	bblanchon/ArduinoJson
	ESP32Async/ESPAsyncTCP
	ESP32Async/ESPAsyncWebServer
	mathieucarbou/MycilaWebSerial
	alanswx/ESPAsyncWiFiManager
	plerup/EspSoftwareSerial
	robtillaart/CRC
	mathieucarbou/OneWire
	gbertaz/NonBlockingDallas
	hmueller01/pubsubclient3

[env:d1_mini]
board = d1_mini
board_build.ldscript = eagle.flash.4m.ld
build_flags = ${env.build_flags}
custom_hardwareserial = false
monitor_filters = esp8266_exception_decoder, default, time, printable, colorize
upload_speed = 921600

[env:WiFi-Dongle]
board = esp12e
board_build.ldscript = eagle.flash.4m.ld
custom_hardwareserial = true
build_flags = ${env.build_flags}
custom_prog_version = ${env.custom_prog_version}
monitor_filters = esp8266_exception_decoder, default, time, printable, colorize
upload_speed = 921600

[env:esp01_1m]
board = esp01_1m
board_build.ldscript = eagle.flash.1m.ld
custom_hardwareserial = true
build_flags = ${env.build_flags}
custom_prog_version = ${env.custom_prog_version}
monitor_filters = esp8266_exception_decoder, default, time, printable, colorize

